services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: deepfake-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DEVICE=cpu
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ../api:/app/api  # On monte tout le dossier api pour être sûr
      - ../mlruns:/app/mlruns
      - ../data:/app/data
      - ../logs:/app/logs
    restart: unless-stopped
    networks:
      - deepfake-network

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit
    container_name: deepfake-frontend
    # Flags essentiels pour éviter le 403 et permettre l'upload
    command: streamlit run frontend/app.py --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000/predict
    volumes:
      - ../frontend:/app/frontend
    restart: unless-stopped
    networks:
      - deepfake-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: deepfake-mlflow
    ports:
      - "5000:5000"
    volumes:
      - ../mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri file:/mlruns --default-artifact-root /mlruns
    restart: unless-stopped
    networks:
      - deepfake-network

networks:
  deepfake-network:
    driver: bridge